name: BlueMapCustomSkinProvider
version: ${project.version}
main: com.technicjelle.bluemapcustomskinprovider.BlueMapCustomSkinProvider
api-version: 1.13
depend:
  - BlueMap
softdepend: [ "SkinsRestorer" ]
authors: [ TechnicJelle, Cerothen ]
description: ${project.description}
website: ${project.url}
loadbefore:
  - BlueMapFloodgate
